spring.application.name=ExpenseAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=Christos20

jwt.secret=ThisIsMyVeryLongSecretKeyForJwtSigning123456789
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true